services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: funcionarios
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  web:
      build: ./backend
      # O comando abaixo agora encontrar√° a pasta 'app' corretamente
      command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      volumes:
        - ./backend:/app
        - ./frontend/templates:/frontend/templates
      ports:
        - "8000:8000"
      depends_on:
        db:
          condition: service_healthy
      environment:
        DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-logindb}
        SECRET_KEY: ${SECRET_KEY:-your-secret-key-here}
        ADMIN_USERNAME: ${ADMIN_USERNAME:-admin}
        ADMIN_PASSWORD: ${ADMIN_PASSWORD:-admin123}
        ADMIN_EMAIL: ${ADMIN_EMAIL:-admin@example.com}

  volumes:
    postgres_data: